config/routes.rb
Rails.application.routes.draw do

  resources :comments
  resources :posts
  resources :kits
  resources :steps
  resources :experiments
  resources :fields
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static#home'
  get '/apod/main' => 'apod#main'
  get '/articles' => 'article#index'
  get '/search' => 'search#index'
  get '/fields/:id/astronomy' => 'fields#astronomy', as: :astro
  get '/fields/:id/chemistry' => 'fields#chemistry', as: :chem
  get '/fields/:id/geology' => 'fields#geology', as: :geo
  get '/experiments/:id(/:pg)' => 'experiments#show', as: :exper
  post '/article/add' => 'article#add', as: :article_add
  post '/article/:id/remove' => 'article#remove', as: :article_remove
  post '/experiments/:id/add' => 'experiments#add', as: :experiment_add
  post '/experiments/:id/remove' => 'experiments#remove', as: :experiment_remove
  get '/:username(/:page)(/:post_id)' => 'static#profile', as: :profile
end

app/models/experiment.rb
class Experiment < ApplicationRecord
  belongs_to :field
  has_many :kits, dependent: :destroy
  has_many :user_experiments, dependent: :destroy
  has_many :users, through: :user_experiments, dependent: :destroy
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/assets/images/default_pic.svg"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  def full_name
    	"#{fname} #{lname}".strip
  end
end

app/controllers/experiments_controller.rb
class ExperimentsController < ApplicationController
  before_action :set_experiment, only: [:show, :edit, :update, :destroy]

  # GET /experiments
  # GET /experiments.json
  def index
    @experiments = Experiment.all
  end

  # GET /experiments/1
  # GET /experiments/1.json
  def show
    @steps = Step.all
    # was:
    # @step = Step.find_by(params[:id])
    # corrected:
    @step = Step.find_by(id: params[:id])
    # @kits = Kit.all
    # @kits = @experiment.kits
    # was:
    # @item = Item.find_by(params[:id])
    # corrected:
    @item = Item.find_by(id: params[:id])
    @posts = Post.all
    @post = params[:post_id] ? Post.find(params[:post_id]) : Post.new
  end

  # Add experiments to userexperiments
  def add
    # define current user
   @user = current_user
    # look for the experiment by experiment.id
   @experiment = Experiment.find(params[:id])
    # define if the userexperiment table exists
   @userexperiment = UserExperiment.find_by(experiment_id: params[:id], user_id: current_user.id)
   if @userexperiment
    #  if it doesnt exist, then push the experiment into the userexperiment join table
   else
     @user.experiments << @experiment
   end
   redirect_back(fallback_location: profile_path(@user.username,:experiment))
  end

  def remove
    @user = current_user
    @experiment = Experiment.find(params[:id])
    @userexperiment = UserExperiment.find_by(experiment_id: params[:id], user_id: current_user.id)
    unless @userexperiment.nil?
      @userexperiment.destroy
    else
    end
    redirect_back(fallback_location: profile_path(@user.username,:experiment))
  end

  # def steps
  # end

  # GET /experiments/new
  def new
    @experiment = Experiment.new
  end

  # GET /experiments/1/edit
  def edit
  end

  # POST /experiments
  # POST /experiments.json
  def create
    @experiment = Experiment.new(experiment_params)

    respond_to do |format|
      if @experiment.save
        format.html { redirect_to @experiment }
        format.json { render :show, status: :created, location: @experiment }
      else
        format.html { render :new }
        format.json { render json: @experiment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /experiments/1
  # PATCH/PUT /experiments/1.json
  def update
    respond_to do |format|
      if @experiment.update(experiment_params)
        format.html { redirect_to @experiment }
        format.json { render :show, status: :ok, location: @experiment }
      else
        format.html { render :edit }
        format.json { render json: @experiment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /experiments/1
  # DELETE /experiments/1.json
  def destroy
    @experiment.destroy
    respond_to do |format|
      format.html { redirect_to experiments_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_experiment
      @experiment = Experiment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def experiment_params
      params.require(:experiment).permit(:title, :overview, :image, :field_id)
    end
end

app/helpers/experiments_helper.rb
module ExperimentsHelper
end

app/views/experiments/_form.html.erb
<%= simple_form_for(@experiment) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :overview %>
    <%= f.input :image %>
    <%= f.association :field %>
    <%# f.select :field, options_for_select( Field.all.map{|s| [s.field]}) %>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/experiments/_posts.html.erb
<div id="experimentPostDiv">
	<h2>Posts</h2><br />
		<% if user_signed_in? %>
			<div class="backTabs">
				<a class="newPostLink" href="/experiments/<%= @experiment.id %>/new">New Post</a><br />
			</div>
		<% end %>
		<% @posts.each do |post| %>
			<% if @experiment == post.experiment %>
				<div class="postPreview">
					<a href="/posts/<%= post.id %>">
						<%= image_tag post.image %><br />
						<%= post.title %>
					</a><br />
					<a href="/<%= post.user.username %>/post"><%= post.user.username %></a><br />
				</div>
			<% elsif post.experiment.nil? %>
				<p>This experiment doesn't have any posts yet.</p>
			<% end %>
		<% end %>
</div>

app/views/experiments/_steps.html.erb
<div id="stepShowDiv">
	<h1>Steps</h1><br />
	<%= render file: "steps/index" %>
</div>

app/views/experiments/edit.html.erb
<% if user_signed_in? && current_user.admin? %>

<div id="editExperDiv">

<h1>Editing Experiment</h1>

	<%= render 'form', experiment: @experiment %>

	<%= link_to 'See Experiment', @experiment %> |
	<%= link_to 'See All Experiments', experiments_path %>

</div>

<% end %>

app/views/experiments/index.html.erb
<div id="experimentIndex">

<div class="h1Div"><h1>Experiments</h1></div><br />
	<% if user_signed_in? && current_user.admin? %>
		<%= link_to 'New Experiment', new_experiment_path %> | 
		<%= link_to 'New Experiment Step', new_step_path %><br />
	<% end %>
  	<% @experiments.each do |experiment| %>
  		<div class="experimentPreview">
			<a href="/experiments/<%= experiment.id %>">

      <div class="experimentImageSpan" style="background:url('<%= experiment.image.url %>'); background-size:cover; background-position:center; background-repeat:no-repeat;">  
      <!-- <br /><br /><br /><br /><br /> -->
      </div>
      <p><strong><%= experiment.title %></strong></p></a>

    		<!-- <h3><%# experiment.title %></h3></a> -->
    		<a href="/fields/<%= experiment.field.id %>"><h4><%= experiment.field.name %></h4></a>
    		<!-- <a href="/experiments/<%# experiment.id %>"><%# image_tag experiment.image %></a><br /> -->
    		<% if user_signed_in? && UserExperiment.find_by(experiment_id: experiment.id, user_id: current_user.id) %>
      			<%= button_to 'Unsave Experiment', experiment_remove_path(experiment) %>
    		<% elsif user_signed_in? %>
      			<%= button_to 'Save Experiment', experiment_add_path(experiment) %>
    		<% end %>
    		<!-- <%# if user_signed_in? && current_user.admin? %>
    			<%# link_to 'Edit', edit_experiment_path(experiment) %> | 
    			<%# link_to 'Delete', experiment, method: :delete, data: { confirm: 'Are you sure?' } %>
  			<%# end %> -->
    	</div>
  	<% end %>
</div>

app/views/experiments/new.html.erb
<% if user_signed_in? && current_user.admin? %>

<div id="newExperimentDiv">

<h1>New Experiment</h1><br />

<%= link_to 'Back To All Experiments', experiments_path %><br /><br />

<%= render 'form', experiment: @experiment %>

</div>

<% end %>

app/views/experiments/show.html.erb
<div id="experimentShowDiv">

  <h1><%= @experiment.title %></h1><br />
  <div class="experimentTabs">
    <!-- Was #stepAnchor before, changed to #steps to try new anchor tag smooth scroll method: -->
    <a class="stepLink scrollLink" id="stepClick" href="/experiments/<%= @experiment.id %>/steps#hiddenDiv">Steps</a>
    <!-- <a class="stepLink<%# " inactive" if params[:pg] == "steps" %>" href="/experiments/<%# @experiment.id %>/steps">Steps</a> -->
    <% if @experiment.kits %>
      <% @experiment.kits.each do |kit| %>
        <a class="kitLink" href="<%= exper_path(@experiment,"kit") %>">Kit</a>
        <span id ="kitModal" class="experiment_panel hideKit<%= " active" if params[:pg] == "kit" %>"><%= render file: 'kits/show', locals: {kit: kit} %><br />
          <button type="button" name="button" onclick="closeModal()">Close</button></span>
      <% end %>
    <% end %>
    <!-- Was #postAnchor before, changed to #posts to try new anchor tag smooth scroll method: -->
    <a class="expPostLink scrollLink" href="/experiments/<%= @experiment.id %>/posts#hiddenDiv">Posts</a>
    <!-- <a class="expPostLink<%# " inactive" if params[:pg] == "posts" %>" href="/experiments/<%# @experiment.id %>/posts">Posts</a> -->
  </div>
  <% if user_signed_in? && current_user.admin? %>
    <br /><%= link_to 'Edit', edit_experiment_path(@experiment) %> | 
    <%= link_to 'Delete', @experiment, method: :delete, data: { confirm: 'Are you sure?' } %>
  <% end %>
    <h3 class="fieldName"><strong>Field:</strong>
    <a href="/fields/<%= @experiment.field.id %>"><%= @experiment.field.name %></a></h3>
    <% if user_signed_in? && UserExperiment.find_by(experiment_id: @experiment.id, user_id: current_user.id) %>
      <%= button_to 'Unsave Experiment', experiment_remove_path(@experiment) %>
    <% elsif not user_signed_in? %>
    <% else %>
      <%= button_to 'Save Experiment', experiment_add_path(@experiment) %>
    <% end %>
    <span class="experimentImageSpan"><%= image_tag @experiment.image %></span><br />
    <%= @experiment.overview %>

    <!-- Previous attempt with anchor tags (before adding smooth scroll): -->
    <!-- <span id="postAnchor"></span>
    <span id="stepAnchor"></span>
    <br />
    <br />
    <br /> -->

  <div id="hiddenDiv">
    <span class="experiment_panel hideSteps<%= " active" if params[:pg] == "steps" %>" id="steps"><%= render 'steps', exper: @experiment %></span>
    <br />
    <span class="experiment_panel hideExpPosts<%= " active" if params[:pg] == "posts" %>" id="posts"><%= render 'posts', exper: @experiment %></span>
    <br />
    <span class="experiment_panel hideNewPostLink<%= " active" if params[:pg] == "new" %>" id="new">
      <h1>New Post</h1><br />
      <%= render 'posts/form', exper: @experiment, method: :new %>
    </span>
  </div>

  <%# link_to 'See All Experiments', experiments_path %>

</div>