config/routes.rb
Rails.application.routes.draw do

  resources :comments
  resources :posts
  resources :kits
  resources :steps
  resources :experiments
  resources :fields
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static#home'
  get '/apod/main' => 'apod#main'
  get '/articles' => 'article#index'
  get '/search' => 'search#index'
  get '/fields/:id/astronomy' => 'fields#astronomy', as: :astro
  get '/fields/:id/chemistry' => 'fields#chemistry', as: :chem
  get '/fields/:id/geology' => 'fields#geology', as: :geo
  get '/experiments/:id(/:pg)' => 'experiments#show', as: :exper
  post '/article/add' => 'article#add', as: :article_add
  post '/article/:id/remove' => 'article#remove', as: :article_remove
  post '/experiments/:id/add' => 'experiments#add', as: :experiment_add
  post '/experiments/:id/remove' => 'experiments#remove', as: :experiment_remove
  get '/:username(/:page)(/:post_id)' => 'static#profile', as: :profile
end

app/models/apod.rb
class Apod < ApplicationRecord
	def self.get_api_info
  		nasa_api = "https://api.nasa.gov/planetary/apod?api_key=#{ENV['APOD_API_KEY']}&count=3"
  		request_to_nasa_api = Net::HTTP.get(URI(nasa_api))
  		results = JSON.parse request_to_nasa_api
	end
end

app/models/article.rb
class Article < ApplicationRecord
	has_many :user_articles, dependent: :destroy
	has_many :users, through: :user_articles, dependent: :destroy

	def self.get_api_info

    # ADDED 7/19 to try to fix API problem:
    require 'net/http'

    # 1) Retrieve all the articles from the database
		news_api = "https://newsapi.org/v1/articles?source=national-geographic&sortBy=top&apiKey=#{ENV['NEWS_API_KEY']}"
		request_to_news_api = Net::HTTP.get(URI(news_api))
		results = JSON.parse request_to_news_api
    #articles = ActiveRecord::Relation.new self, :articles, self.predicate_builder
    articles = []
    # 2) Verify we have the articles in the database
		results["articles"].each do |article|
      db_article = self.find_by(alink: article["url"])
      # if we don't have one, add it
      unless db_article
        db_article = Article.create(
          alink: article["url"],
          picture: article["urlToImage"],
          name: article["title"],
          overview: article["description"],
          date: article["publishedAt"]
        )
      end
      articles << db_article
    end
    articles
	end

  def favorited? user
    user.user_articles.find_by( article_id: self.id )
  end

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/experiment.rb
class Experiment < ApplicationRecord
  belongs_to :field
  has_many :kits, dependent: :destroy
  has_many :user_experiments, dependent: :destroy
  has_many :users, through: :user_experiments, dependent: :destroy
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/assets/images/default_pic.svg"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  def full_name
    	"#{fname} #{lname}".strip
  end
end

app/models/field.rb
class Field < ApplicationRecord
	has_many :user_fields, dependent: :destroy
  	has_many :users, through: :user_fields
  	has_many :experiments
  	has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/assets/images/default_pic.svg"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/item.rb
class Item < ApplicationRecord
	has_many :kit_items, dependent: :destroy
	has_many :kits, through: :kit_items
end

app/models/kit.rb
class Kit < ApplicationRecord
  belongs_to :experiment
  has_many :kit_items, dependent: :destroy
  has_many :items, through: :kit_items, dependent: :destroy
  has_many :user_kits, dependent: :destroy
  has_many :users, through: :user_kits, dependent: :destroy
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/assets/images/default_pic.svg"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/kit_item.rb
class KitItem < ApplicationRecord
	belongs_to :kit
	belongs_to :item
end

app/models/location.rb
class Location < ApplicationRecord
	has_many :users
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :experiment
  has_many :comments, dependent: :destroy
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/assets/images/default_pic.svg"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/search.rb
class Search < ApplicationRecord
end

app/models/static.rb
class Static < ApplicationRecord
	def self.get_api_info
		news_api = "https://newsapi.org/v1/articles?source=national-geographic&sortBy=top&apiKey=#{ENV['NEWS_API_KEY']}"
		request_to_news_api = Net::HTTP.get(URI(news_api))
		results = JSON.parse request_to_news_api
		results["articles"]
	end
end

app/models/step.rb
class Step < ApplicationRecord
  belongs_to :experiment
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/assets/images/default_pic.svg"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :location
  has_many :user_fields, dependent: :destroy
  has_many :fields, through: :user_fields
  has_many :user_experiments, dependent: :destroy
  has_many :experiments, through: :user_experiments
  has_many :user_kits, dependent: :destroy
  has_many :kits, through: :user_kits
  has_many :kit_items
  has_many :items, through: :kit_items
  has_many :user_articles, dependent: :destroy
  has_many :articles, through: :user_articles
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_attached_file :propic, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/assets/default/:style/default_pic.png"
  validates_attachment_content_type :propic, content_type: /\Aimage\/.*\z/
  validates :username, :presence => true, :uniqueness => { :case_sensitive => false }
  def full_name
    "#{fname} #{lname}".strip
  end

end

app/models/user_article.rb
class UserArticle < ApplicationRecord
	belongs_to :user
	belongs_to :article
end

app/models/user_field.rb
class UserField < ApplicationRecord
	belongs_to :user
	belongs_to :field
end

app/models/user_kit.rb
class UserKit < ApplicationRecord
	belongs_to :user
	belongs_to :kit
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @user = User.find_by(params[:username])
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    # @post = Post.find(params[:post_id])
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.comments.destroy_all
    @post.destroy
    respond_to do |format|
      format.html { redirect_to profile_path(current_user.username,:post) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :image, :user_id, :experiment_id)
    end
end

app/helpers/apod_helper.rb
module ApodHelper
end

app/helpers/fields_helper.rb
module FieldsHelper
end

app/helpers/kits_helper.rb
module KitsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/steps_helper.rb
module StepsHelper
end

app/views/posts/_form.html.erb
<%= simple_form_for(@post) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <br /><br />
    <%= f.input :title %>
    <%= f.input :body %>
    <%= f.input :image %>
    <% if ((defined?(exper)).nil? == false) && exper.id %>
      <%= f.input :experiment_id, as: :hidden, input_html: { value: exper.id } %>
    <% else %>
      <%= f.association :experiment, input_html: {id: 'post.experiment_id', value: @post.experiment_id} %>
    <% end %>
  </div>  

  <div class="form-actions">
    <%= f.button :submit %><br /><br />
  </div>
<% end %>

app/views/posts/edit.html.erb
<% if user_signed_in? && current_user.admin? %>
	<h1>Editing Post</h1>

	<%= render 'form', post: @post %>

	<%= link_to 'Back to Post', @post %> |
	<%= link_to 'Post Feed', posts_path %>
<% end %>

app/views/posts/index.html.erb
<div id="postFeedDiv">
<h1>Post Feed</h1><br />
  <% @posts.each do |post| %>
    <div class="postPreview">
      <a href="/posts/<%= post.id %>">
      <%= image_tag post.image %><br />
      <%= post.title %></a><br />
      <a href="/<%= post.user.username %>/post">
      <%= post.user.username %></a><br />
        <% if user_signed_in? && current_user.admin? %>
          <%# link_to 'Edit', edit_post_path(post) %>
          <%= link_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>
    </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<% if user_signed_in? && current_user.admin? %>

	<h1>New Post</h1>

	<%= render 'form', post: @post %>

	<%= link_to 'Post Feed', posts_path %>
<% end %>

app/views/posts/show.html.erb
<div id="postShowDiv">
  <h1><%= @post.title %></h1><br />
    <a href="/<%= @post.user.username %>/post"><h3><%= @post.user.username %></h3></a>
    <a href="/experiments/<%= @post.experiment.id %>"><h4>Experiment: <%= @post.experiment.title %></h4></a>
    <%= image_tag @post.image %><br />
    <%= @post.body %><br /><br />

    <% if @post.user == current_user %>
      <a class="editPostsLink" href="/<%= @post.user.username %>/edit/<%= @post.id %>">Edit</a> | 
      <%= link_to 'Delete', @post, method: :delete, remote: true, data: { confirm: 'Are you sure?' } %><br />
      <%# link_to 'Edit', edit_post_path(@post) %> 
      <%# link_to 'My Posts', profile_path(@post.user.username,:post) %>
    <% end %>

    <%# link_to 'Post Feed', posts_path %>
</div>