config/routes.rb
Rails.application.routes.draw do

  resources :comments
  resources :posts
  resources :kits
  resources :steps
  resources :experiments
  resources :fields
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static#home'
  get '/apod/main' => 'apod#main'
  get '/articles' => 'article#index'
  get '/search' => 'search#index'
  get '/fields/:id/astronomy' => 'fields#astronomy', as: :astro
  get '/fields/:id/chemistry' => 'fields#chemistry', as: :chem
  get '/fields/:id/geology' => 'fields#geology', as: :geo
  get '/experiments/:id(/:pg)' => 'experiments#show', as: :exper
  post '/article/add' => 'article#add', as: :article_add
  post '/article/:id/remove' => 'article#remove', as: :article_remove
  post '/experiments/:id/add' => 'experiments#add', as: :experiment_add
  post '/experiments/:id/remove' => 'experiments#remove', as: :experiment_remove
  get '/:username(/:page)(/:post_id)' => 'static#profile', as: :profile
end

app/models/field.rb
class Field < ApplicationRecord
	has_many :user_fields, dependent: :destroy
  	has_many :users, through: :user_fields
  	has_many :experiments
  	has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/assets/images/default_pic.svg"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/controllers/fields_controller.rb
class FieldsController < ApplicationController
  before_action :set_field, only: [:show, :edit, :update, :destroy]

  # GET /fields
  # GET /fields.json
  def index
    @fields = Field.all
  end

  # GET /fields/1
  # GET /fields/1.json
  def show
    @field = Field.find(params[:id])
  end

  # GET /fields/new
  def new
    @field = Field.new
  end

  # GET /fields/1/edit
  def edit
  end

  def astronomy
    @field = Field.find(params[:id])
  end

  def chemistry
    @field = Field.find(params[:id])
  end

  def geology
    @field = Field.find(params[:id])
  end

  # # GET /fields/tiltscroll
  # def tiltscroll
  # end

  # POST /fields
  # POST /fields.json
  def create
    @field = Field.new(field_params)

    respond_to do |format|
      if @field.save
        format.html { redirect_to @field, notice: 'Field was successfully created.' }
        format.json { render :show, status: :created, location: @field }
      else
        format.html { render :new }
        format.json { render json: @field.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fields/1
  # PATCH/PUT /fields/1.json
  def update
    respond_to do |format|
      if @field.update(field_params)
        format.html { redirect_to @field, notice: 'Field was successfully updated.' }
        format.json { render :show, status: :ok, location: @field }
      else
        format.html { render :edit }
        format.json { render json: @field.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fields/1
  # DELETE /fields/1.json
  def destroy
    @field.destroy
    respond_to do |format|
      format.html { redirect_to fields_url, notice: 'Field was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_field
      @field = Field.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def field_params
      params.require(:field).permit(:name, :overview, :image)
    end
end

app/helpers/fields_helper.rb
module FieldsHelper
end

app/views/fields/_form.html.erb
<%= simple_form_for(@field) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :overview %>
    <%= f.input :image %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/fields/astronomy.html.erb
<div id="stickyNav">

<!-- <div class="ar"></div> -->
<section class="section first" style="background: url('/assets/astro1.jpg'); background-size: cover;     background-attachment: fixed;">
<div class="ar"></div>
  <span class ="fieldName astronomyName">Astronomy</span>
  
</section>
<section class="section second" style="background: url('/assets/astro2.jpg'); background-size: cover;     background-attachment: fixed;">
  <span>Check out pictures from NASA's Astronomy Picture Of The Day program</span><br /><br />
  <a class="apodLink" href="/apod/main">Go Star Searching</a>
  
</section>
<section class="section third" style="background: url('/assets/astro3.jpg'); background-size: cover;     background-attachment: fixed;">
  <span>Browse all experiments related to astronomy:</span><br /><br />
    <% if @field.experiments %>
      <% @field.experiments.each do |experiment| %>
        <a href="/experiments/<%= experiment.id %>"><%= experiment.title %></a><br />
      <% end %>
    <% else %>
      <h4>No experiments for this field yet.  Coming Soon!</h4>
    <% end %>
  
</section>
<section class="section final" style="background: url('/assets/astro1.jpg'); background-size: cover;     background-attachment: fixed;">
  
</section>
<div id="astroPattern" class="pattern-overlay">
    <!-- <h3>This is the last section.</h3> -->
    <p>Covering everything from eclipses to solar flares to black holes, astronomy is (literally) an ever-expanding field.  Look around and let your imagination run wild!</p>
</div>

</div>

app/views/fields/chemistry.html.erb
<div id="stickyNav">

<!-- <div class="ar"></div> -->
<section class="section first" style="background: url('/assets/chem_bg1.jpg'); background-size: cover;     background-attachment: fixed;">
<div class="ar"></div>
  <span class ="fieldName chemName">Chemistry</span>
  
</section>
<section class="section second" style="background: url('/assets/chem_bg2.jpg'); background-size: cover;     background-attachment: fixed;">
  <span>Check out *fun chemistry videos/facts/etc*</span><br /><br />
  <!-- <a class="apodLink" href="/apod/main">Go Star Searching</a> -->
  
</section>
<section class="section third" style="background: url('/assets/chem_bg3.jpg'); background-size: cover;     background-attachment: fixed;">
  <span>Browse all experiments related to chemistry:</span><br /><br />
    <% if @field.experiments %>
      <% @field.experiments.each do |experiment| %>
        <a href="/experiments/<%= experiment.id %>"><%= experiment.title %></a><br />
      <% end %>
    <% else %>
      <h4>No experiments for this field yet.  Coming Soon!</h4>
    <% end %>
  
</section>
<section class="section final" style="background: url('/assets/chem_bg1.jpg'); background-size: cover;     background-attachment: fixed;">
  
</section>
<div id="chemPattern" class="pattern-overlay">
    <!-- <h3>This is the last section.</h3> -->
    <p>Chemistry is awesome.  Need proof?  Check out what it can do!</p>
    <iframe width="560" height="315" src="https://www.youtube.com/embed/qkj2UqvBnzQ?rel=0&amp;showinfo=0&amp;controls=1" frameborder="0" allowfullscreen></iframe>
</div>

</div>

app/views/fields/edit.html.erb
<% if user_signed_in? && current_user.admin? %>

<h1>Editing Field</h1>

<%= render 'form', field: @field %>

<%= link_to 'See Field', @field %> |
<%= link_to 'See All Fields', fields_path %>

<% end %>

app/views/fields/geology.html.erb
<div id="stickyNav">

<!-- <div class="ar"></div> -->
<section class="section first" style="background: url('/assets/geology.jpg'); background-size: cover;     background-attachment: fixed;">
<div class="ar"></div>
  <span class ="geoName fieldName">Geology</span>
  
</section>
<section class="section second" style="background: url('/assets/earthsci1.jpg'); background-size: cover;     background-attachment: fixed;">
  <span>Check out *fun geology videos/facts/etc*</span><br /><br />
  <!-- <a class="apodLink" href="/apod/main">Go Star Searching</a> -->
  
</section>
<section class="section third" style="background: url('/assets/geology2.jpg'); background-size: cover;     background-attachment: fixed;">
  <span>Browse all experiments related to geology:</span><br /><br />
    <% if @field.experiments %>
      <% @field.experiments.each do |experiment| %>
        <a href="/experiments/<%= experiment.id %>"><%= experiment.title %></a><br />
      <% end %>
    <% else %>
      <h4>No experiments for this field yet.  Coming Soon!</h4>
    <% end %>
  
</section>
<section class="section final" style="background: url('/assets/geology.jpg'); background-size: cover;     background-attachment: fixed;">
  
</section>
<div id="geoPattern" class="pattern-overlay">
    <!-- <h3>This is the last section.</h3> -->
    <p>Covering everything from volcanoes to glacial valleys, geology rocks!</p>
</div>

</div>

app/views/fields/index.html.erb
<div id="fieldIndexDiv">
<h1>Fields</h1><br />
	<% if user_signed_in? && current_user.admin? %>
		<%= link_to 'New Field', new_field_path %><br />
	<% end %>
  <% @fields.each do |field| %>
  	<div class="fieldPreview">
    	<a href="/fields/<%= field.id %>">
    	<div class="fieldImageSpan" style="background:url('<%= field.image.url %>'); background-size:cover; background-position:center; background-repeat:no-repeat;">	<br /><br /><br /><br /><br /><h2><strong><%= field.name %></strong></h2></div></a>
    	<% if user_signed_in? && current_user.admin? %>
    		<%= link_to 'Edit', edit_field_path(field) %> | 
    		<%= link_to 'Destroy', field, method: :delete, data: { confirm: 'Are you sure?' } %>
    	<% end %>
    </div>
  <% end %>
</div>









<%# render file: 'fields/tiltscroll' %>

app/views/fields/new.html.erb
<% if user_signed_in? && current_user.admin? %>

<h1>New Field</h1>

<%= render 'form', field: @field %>

<%= link_to 'All Fields', fields_path %>

<% end %>

app/views/fields/show.html.erb
<% if @field.id == 1 %>
	<%= render file: '/fields/astronomy', as: astro_path %>
<% elsif @field.id == 2 %>
	<%= render file: '/fields/chemistry', as: chem_path %>
<% elsif @field.id == 3 %>
	<%= render file: '/fields/geology', as: geo_path %>
<% else %>

<div id="fieldShowDiv">
  <h1><%= @field.name %></h1><br /><br />
  <span class="fieldShowImage"><%= image_tag @field.image %></span><br /><br />
  <%= @field.overview %><br /><br />

<p>
  <strong>Experiments:</strong>
<% if @field.experiments %>
	<% @field.experiments.each do |experiment| %>
		<a href="/experiments/<%= experiment.id %>"><%= experiment.title %></a><br />
	<% end %>
<% else %>
	<p>Sorry, no experiments in this field yet... coming soon!</p>
<% end%>
</p>

<br /><br />
<% if user_signed_in? && current_user.admin? %>
	<%= link_to 'Edit', edit_field_path(@field) %><br />
<% end %>
<%# link_to 'See All Fields', fields_path %>
</div>

<% end %>

app/views/fields/tiltscroll.html.erb
<div class="main">
	    <div class="header">
        <h1>Fields</h1>
        <h2>Browse Scientific Fields</h2>
  	  </div>
  	  <section class="page1">
        <div class="page_container">
          <h1><a href="http://www.bucketlistly.com/achievements/visit-sydney-australia-95861" target="_blank">Travel to Sydney, Australia<br><small>Completed on 14 Feb 2014</small></a></h1>
        </div>
      </section>
  	  <section class="page2">
        <div class="page_container">
          <h1><a href="http://www.bucketlistly.com/achievements/visit-uluru-ayers-rock-96722" target="_blank">Visit Uluru (Ayers Rock), Australia<br><small>Completed on 17 Feb 2014</small></a></h1>
        </div>
      </section>
  	  <section class="page3">
        <div class="page_container">
          <h1><a href="http://www.bucketlistly.com/achievements/travel-to-zhangjiajie-avatar-s-mountains-china-85798" target="_blank">Travel to ZhangJiaJie (Avatar's Mountain) in China<br><small>Completed on 20 Jan 2014</small></a></h1>
        </div>
      </section>
  	  <section class="page4">
        <div class="page_container">
          <h1><a href="http://www.bucketlistly.com/achievements/ride-a-camel-93541" target="_blank">Ride a Camel in the Australian Outback<br><small>Completed on 17 Feb 2014</small></a></h1>
        </div>
      </section>
  	  <section class="page5">
        <div class="page_container">
          <h1><a href="http://www.bucketlistly.com/achievements/visit-sydney-australia-95861" target="_blank">Travel to Sydney, Australia<br><small>Completed on 14 Feb 2014</small></a></h1>
        </div>
      </section>
  	  <section class="page6">
        <div class="page_container">
          <h1><a href="http://www.bucketlistly.com/achievements/visit-uluru-ayers-rock-96722" target="_blank">Visit Uluru (Ayers Rock), Australia<br><small>Completed on 17 Feb 2014</small></a></h1>
        </div>
      </section>
  	  <section class="page7">
        <div class="page_container">
          <h1><a href="http://www.bucketlistly.com/achievements/travel-to-zhangjiajie-avatar-s-mountains-china-85798" target="_blank">Travel to ZhangJiaJie (Avatar's Mountain) in China<br><small>Completed on 20 Jan 2014</small></a></h1>
        </div>
      </section>
  	  <section class="page8">
        <div class="page_container">
          <h1><a href="http://www.bucketlistly.com/achievements/ride-a-camel-93541" target="_blank">Ride a Camel in the Australian Outback<br><small>Completed on 17 Feb 2014</small></a></h1>
        </div>
      </section>
    </div>